### ISSUE TITLE
Total number of warnings and errors

### ISSUE THREAD

**Issue by reardestani** [EdgedesignCZ/phpqa#103]
Very helpful package. Thanks.

Is there any way we can only **get total number of errors and warnings** in terminal? 

We need to save it as a **env variables** when we are merging the codes to master then we pass the variable for allowed warnings for next PR check.

**Comment by zdenekdrahos** [comment]
Can you use [errors count](https://github.com/EdgedesignCZ/phpqa#exit-code) from console output?

```bash
# 1. save phpqa console output to file
bin/ci.sh > out.log
# 2. extract errors count
cat out.log | grep "phpqa.html " | cut -d "|" -f4 | awk '{$1=$1;print}'
```

_Ad 2. print output -> find phpqa summary line -> extract errors count -> [trim whitespace](https://unix.stackexchange.com/a/205854)_

**Comment by reardestani** [comment]
Thanks, it works fine.
I was not thinking about this solution. I thought, there is a feature and I am missing that.
