### ISSUE TITLE
PHP-Parallel-Lint should support the extensions

### ISSUE THREAD

**Issue by paolomainardi** [EdgedesignCZ/phpqa#104]
It seems that the --extensions arguments is ignored by parallel-linter command, you know better than me that most of the times just "php" extension is not enough, i'll try in the next few days to implement it.

**Comment by sarcisal** [comment]
Hi Paolo,
I had the same problem with phpcs tool. But I understood the issue when I saw the following comments on a thread for Drupal 8:
- https://www.drupal.org/project/coder/issues/2867601#comment-12036796
- https://www.drupal.org/project/coder/issues/2867601#comment-12075633
I hope they will be useful

**Comment by paolomainardi** [comment]
Thanks a lot!
