### ISSUE TITLE
Parse phpstan output

### ISSUE THREAD

**Issue by ndench** [EdgedesignCZ/phpqa#108]
It would be great if the phpstan output was parsed the same as the output from the other tools. At the moment no matter how many errors phpstan reports, phpqa reports it as a single error as you can see here: 
![2018-02-08_17-08-15](https://user-images.githubusercontent.com/2062388/35959757-ae10e374-0cf2-11e8-8882-27033f2345d0.png)

Here is an example of the current phpstan output:
![2018-02-08_17-07-52](https://user-images.githubusercontent.com/2062388/35959790-c24419b0-0cf2-11e8-924c-2635ca05ab2e.png)

And here is an example of the psalm output, which is the same as the other linting tools:
![2018-02-08_17-07-40](https://user-images.githubusercontent.com/2062388/35959805-d00618be-0cf2-11e8-9524-424c324b5b0f.png)

**Comment by zdenekdrahos** [comment]
Agree. phpstan supports checkstyle from [v0.8](https://github.com/phpstan/phpstan/releases/tag/0.8), so I'll add it to phpqa.
