### ISSUE TITLE
Add support for wapmorgan/PhpCodeAnalyzer

### ISSUE THREAD

**Issue by MacFJA** [EdgedesignCZ/phpqa#113]
Add the support of the tool [wapmorgan/PhpCodeAnalyzer: PhpCodeAnalyzer finds usage of non-built-in extensions in your php code.](https://github.com/wapmorgan/PhpCodeAnalyzer)

---

The tool don't have XML output. (And adding it look pretty difficult)

**Comment by zdenekdrahos** [comment]
Closing, please see https://github.com/EdgedesignCZ/phpqa/issues/112#issuecomment-369987327
