### ISSUE TITLE
Add support for wapmorgan/php-code-fixer

### ISSUE THREAD

**Issue by MacFJA** [EdgedesignCZ/phpqa#114]
Add support for tool [wapmorgan/php-code-fixer: PhpCodeFixer finds usage of deprecated functions, variables and ini directives in your php code.](http://wapmorgan.github.io/PhpCodeFixer/)

---

The tool don't have XML Output.
The tool return `1` if an error exist

**Comment by zdenekdrahos** [comment]
Closing, please see https://github.com/EdgedesignCZ/phpqa/issues/112#issuecomment-369987327
