### ISSUE TITLE
PHPUnit and issues with html code coverage

### ISSUE THREAD

**Issue by auroraeosrose** [EdgedesignCZ/phpqa#137]
When using 

```yml
phpunit:
     config: phpunit.xml
     reports:
        file:
            coverage: [html]
```
This creates incorrect command line arguments and menu items for html code coverage

First - the --coverage-html argument takes a directory path, NOT a filename.  If you send it a filename it treats it as a directory name
Second the men item says "coverage.html" and links to "coverage.html.html" - which is in fact a directory 

I've changed the code in Phpunit.php to cover the "weird" use case of coverage in html format with a special path for the coverage format when html is selected.  It detects that the format is coverage and the format is html, creates a filename as a directory name for the arguments, and creates a menu item in userReports that links to the index.html in the code coverage directory

```php
            foreach ($this->config->value('phpunit.reports.file') as $report => $formats) {
                foreach ($formats as $format) {
                    if($report == 'coverage' && $format == 'html') {
                        $filename = "{$report}-{$format}";
                        $args["{$report}-{$format}"] = $this->options->toFile($filename);
                        $this->tool->userReports["{$report}.{$format}"] = $this->options->rawFile($filename . '/index.html');
                    } else {
                        $extension = array_key_exists($format, $extensions) ? $extensions[$format] : $format;
                        $filename = "{$report}-{$format}.{$extension}";
                        $args["{$report}-{$format}"] = $this->options->toFile($filename);
                        $this->tool->userReports["{$report}.{$format}"] = $this->options->rawFile($filename);
                    }
                }
            }
```

I've tested this with all the other code coverage, testdoxs, and log output

**Comment by auroraeosrose** [comment]
The most important thing here is really the change in the user report link
if you're running this as a local file:\\\ and not in a webserver you'll link into a directory instead of linking to the index.html file inside the code coverage directory - which is annoying :)

**Comment by almare** [comment]
I work with gitlab and stumbled about a problem with the text report. Gitlab supports the parsing of  the console output to show the coverage in the gitlab ui. My problem is now, if I activate the text coverage I get a text file coverage report. This is how it is designed and works as expected, but for this usecase it would be better to remove the reports path.
Example: 
`"/.composer/vendor/edgedesign/phpqa/../../../vendor/bin/phpunit" --configuration="/app/custom/plugins/omnotosteel/dev-ops/gitlab-ci/phpunit.xml" --log-junit="reports/log-junit.xml" --coverage-html="reports/coverage-html/" --coverage-clover="reports/coverage-clover.xml" --coverage-text="reports/coverage-text.txt"`

it should be 
`"/.composer/vendor/edgedesign/phpqa/../../../vendor/bin/phpunit" --configuration="/app/custom/plugins/omnotosteel/dev-ops/gitlab-ci/phpunit.xml" --log-junit="reports/log-junit.xml" --coverage-html="reports/coverage-html/" --coverage-clover="reports/coverage-clover.xml" --coverage-text --colors=never`

This changes print out the text report on the command line and can be parsed from gitlab.

Do you think this is possible?

**Comment by almare** [comment]
For others with the similar problem. As a workaround I made a cat command on the created coverage-text.html to get it work .

**Comment by zdenekdrahos** [comment]
@almare: configure it in `phpunit.xml` and not in `.phpqa.yml`, if you don't like `cat reports/coverage-text.txt`.

See https://phpunit.de/manual/6.5/en/appendixes.configuration.html#appendixes.configuration.logging

```xml
<?xml version="1.0" encoding="UTF-8"?>

<phpunit>
  <logging>
    <log type="coverage-text" target="php://stdout" />
  </logging>
</phpunit>
```

**Comment by almare** [comment]
Oh man! Shame on me... Once again RTFM... Thank you for your suggestion.

**Comment by almare** [comment]
I tried your suggestion and I found out that the --coverage-text="reports/coverage-text.txt" override the settings of the phpunit.xml setting. So this is unfortunately not the solution. So it still looks like the cat command if for the moment the only solution. Do you think we can add a configuration to phpqa.yml?

**Comment by zdenekdrahos** [comment]
@almare: it's a solution, if you don't configure `coverage: [txt]` in [.phpqa.yml](https://github.com/EdgedesignCZ/phpqa/blob/master/.phpqa.yml#L69).

If phpqa [adds `reports/coverage-text.txt`](https://github.com/EdgedesignCZ/phpqa/blob/master/src/Tools/Analyzer/Phpunit.php#L24), then it must be configured in `.phpqa.yml`

```yaml
phpunit:
    binary: vendor/bin/phpunit
    config: phpunit.xml
    reports:
       # cannot contain `coverage: [txt]`
        file: []
``` 

You'll never get both outputs in single phpqa command. Choose creating txt file, or priting coverage to stdout.
