### ISSUE TITLE
PHPStan errorFormat deprecation

### ISSUE THREAD

**Issue by aeimer** [EdgedesignCZ/phpqa#150]
PHPstan currently prints:

`Note: Using the option --errorFormat is deprecated. Use --error-format instead.`

**Comment by aeimer** [comment]
It seems like the deprecation can be fixed here: https://github.com/EdgedesignCZ/phpqa/blob/e14de0ea33a0a50545bbc11e579102cc73fcdd1a/src/Tools/Analyzer/Phpstan.php#L55

?!

**Comment by zdenekdrahos** [comment]
> analyse command: --error-format is encouraged instead of --errorFormat, with backwards compatibility
> https://github.com/phpstan/phpstan/releases/tag/0.10.3

It's a backward compatible, so we can keep `errorFormat`. `error-format` isn't a backward compatible, It wouldn't work in versions released before 0.10.3.

Feel free to send a PR with backward compatible `Edge\QA\Tools\Analyzer\Phpstan` _(phpstan version must be detected)_. It seems too much trouble for such insignificant notice.

**Comment by hrodic** [comment]
This fix does not seems to work inside a dockerized environment when dependencies are installed as global composer.
I have phpstan 0.12 and still is trying to use --errorFormat old parameter name.
