### ISSUE TITLE
History and evolution of metrics

### ISSUE THREAD

**Issue by VincentClair** [EdgedesignCZ/phpqa#151]
Hello,

Is there a plan to make an history of results and compare them to see evolution through time and versions ? Something as sonar

**Comment by zdenekdrahos** [comment]
I know what you mean. But isn't that a job for CI platform?

We had trends in Jenkins _(its plugins analyzed [XML files from phpqa](https://github.com/EdgedesignCZ/phpqa#output-modes))_. I'm not sure if it should be part of [analyzers](https://github.com/EdgedesignCZ/phpqa#available-tools). You don't have a history in phploc, phpmd, ...

![](https://blog.octo.com/wp-content/uploads/2012/08/screenshot-dashboard-jenkins1.png)
