### ISSUE TITLE
Psalm v3 support?

### ISSUE THREAD

**Issue by mickaelandrieu** [EdgedesignCZ/phpqa#159]
Hi!

I'd like to use Psalm v3 but for now it doesn't works, what can I do to add support of Psalm v3 (ideally with PHPUnit plugin) into phpqa?

Mickaël

Thanks for your awesome project :heart:

**Comment by zdenekdrahos** [comment]
What doesn't work?
_Psalm v3 should work in [v1.20](https://github.com/EdgedesignCZ/phpqa/releases/tag/v1.20.0) (https://github.com/EdgedesignCZ/phpqa/pull/157). Travis looks ok with [psalm v3.0.7](https://travis-ci.org/EdgedesignCZ/phpqa/jobs/471323875#L842)_

![screenshot from 2019-01-08 15 37 06](https://user-images.githubusercontent.com/7994022/50837166-47427480-135b-11e9-816e-9e51b93366d7.png)

**Comment by mickaelandrieu** [comment]
When I require phpqa I get 1.4.3 from Composer, I don't know why I have PHP 7.2 installled on my computer (ubuntu-like).

**Comment by mickaelandrieu** [comment]
Ok problem solved, thanks !

**Comment by mickaelandrieu** [comment]
Sorry for reopening, but looks like it doesn't works (at least using the docker image).

Any ideas?

https://travis-ci.com/PrestaShop/circuit-breaker/jobs/169267177#L631

This is my travis file => https://github.com/PrestaShop/circuit-breaker/blob/master/.travis.yml

**Comment by mickaelandrieu** [comment]
Back again, and investigating on it it looks like the ignoredDirs option is ... ignored.

https://travis-ci.com/PrestaShop/circuit-breaker/jobs/169270975#L857

**Comment by zdenekdrahos** [comment]
Well, the docker image does not include latest versions.

[![travis build for php 7.0 uses same installation like docker image](https://user-images.githubusercontent.com/7994022/50918672-2a806c80-1441-11e9-898b-13e46695e162.png)](https://travis-ci.org/EdgedesignCZ/phpqa/jobs/471323874#L632)

You could build your own docker image with required versions. Or install [phpqa via composer](https://github.com/EdgedesignCZ/phpqa#fake-global-installation-in-local-project). Then you can [install whatever version you like](https://github.com/EdgedesignCZ/phpqa/blob/master/.travis.yml#L24).

**Comment by mickaelandrieu** [comment]
Yes, you're right :)


Thanks for your help, this time it's closed for sure :+1:
