### ISSUE TITLE
Elastic Integration

### ISSUE THREAD

**Issue by Stolr** [EdgedesignCZ/phpqa#161]
Hi ,

Great tools :)

Is there any possibility to send all output data to ElasticSearch ?

This will allow to build graph using Graphana for example that could indicate the evolution of our tests

**Comment by zdenekdrahos** [comment]
I don't think that's a job for phpqa, please see https://github.com/EdgedesignCZ/phpqa/issues/151#issuecomment-428948890
_You have to process files after phpqa. For example, we've pushed them to [Circle CI artifacts directory](https://github.com/EdgedesignCZ/phpqa#circleci---artifacts--global-installation)._
