### ISSUE TITLE
 http://security.sensiolabs.org/check_lock is no longer aivailable.

### ISSUE THREAD

**Issue by Moosh-be** [EdgedesignCZ/phpqa#162]
in phpqa/src/Tools/Analyzer/SecurityChecker.php
```

   if (getenv('TRAVIS_COMMIT')) {
            $args['end-point'] = 'http://security.sensiolabs.org/check_lock';
   }
```

but  http://security.sensiolabs.org/check_lock is no longer aivailable.

So -> 

```
 [Edge\QA\Task\ParallelExec]  '"...ws/vendor/edgedesign/phpqa/../../../vendor/bin/security-checker" security:check ./composer.lock --end-point=http://security.sensiolabs.org/check_lock' exited with code 1 
```

```
 $ vendor/bin/security-checker security:check
 Symfony Security Check Report
 =============================
 No packages have known vulnerabilities.
 The command "vendor/bin/security-checker security:check" exited with 0.
```

**Comment by Moosh-be** [comment]
https://twitter.com/fabpot/status/1099994260051582978

**Comment by Moosh-be** [comment]
the new repo is https://security.symfony.com/check_lock

**Comment by zdenekdrahos** [comment]
Does Travis work with https endpoint?
There was a trouble with it, see https://github.com/EdgedesignCZ/phpqa/commit/4c483c163b8e9c49eaca5cc34a9e74dc866b1a45#diff-6382246a7e016c52f923055e63610142

**Comment by Moosh-be** [comment]
Yepee. Thank you (also for twig upgrade)
