### ISSUE TITLE
Mistake between config and report file

### ISSUE THREAD

**Issue by webaaz** [EdgedesignCZ/phpqa#165]
Hi!

in src/Tools/Tool.php::saveDynamicConfig(), $file is defined in relation with ouput command line option. 
This var is used in src/Tools/Analyzer/Psalm.php::__invoke() to prepare psalm command line.
The config arg is defined by the return of src/Tools/Tool.php::saveDynamicConfig()

What report between result file and config file? I've defined a psalm.config key in my .phpqa.yml file and I want to use it!

Can you explain that?

Best regards

**Comment by zdenekdrahos** [comment]
I don't understand what mistake are you talking about.

_How it works:_

1. [.phpqa.yml](https://github.com/EdgedesignCZ/phpqa/blob/v1.20.0/.phpqa.yml#L66) defines path to xml file
2. [phpqa](https://github.com/EdgedesignCZ/phpqa/blob/v1.20.0/src/Tools/Analyzer/Psalm.php#L46) adds analyzed and ignored files to XML
3. updated XML is [saved in `--buildDir`](https://github.com/EdgedesignCZ/phpqa/blob/v1.20.0/src/Tools/Analyzer/Psalm.php#L26)

**Comment by webaaz** [comment]
My config file .phpqa.yml :

```yaml
psalm:
  allowedErrorsCount: 0
  deadCode: true
  config: .ci/psalm.xml
```
My psalm config file .ci/psalm.xml :

```xml :
<?xml version="1.0"?>
<psalm
        name="Psalm config"
        useDocblockTypes="true"
        totallyTyped="false"
>
    <issueHandlers>
        <LessSpecificReturnType errorLevel="info" />

        <!-- level 3 issues - slightly lazy code writing, but provably low false-negatives -->
        <DeprecatedMethod errorLevel="info" />

        <MissingClosureReturnType errorLevel="info" />
        <MissingReturnType errorLevel="info" />
        <MissingPropertyType errorLevel="info" />
        <InvalidDocblock errorLevel="info" />
        <MisplacedRequiredParam errorLevel="info" />

        <PropertyNotSetInConstructor errorLevel="info" />
        <MissingConstructor errorLevel="info" />
    </issueHandlers>
</psalm>
```
My command line :
```
./vendor/bin/phpqa --report --buildDir .ci/build --analyzedDirs src,tests --tools psalm
```

My result :
```xml
<?xml version="1.0" encoding="UTF-8"?>
<report>
  <item>
    <severity>error</severity>
    <line_from>8</line_from>
    <line_to>8</line_to>
    <type>UnusedClass</type>
    <message>Class App\Controller\DefaultController is never used</message>
    <file_name>src/Controller/DefaultController.php</file_name>
    <file_path>/var/www/src/Controller/DefaultController.php</file_path>
    <snippet>class DefaultController extends AbstractController</snippet>
    <selected_text>class DefaultController extends AbstractController</selected_text>
    <from>147</from>
    <to>197</to>
    <snippet_from>147</snippet_from>
    <snippet_to>197</snippet_to>
    <column_from>1</column_from>
    <column_to>51</column_to>
  </item>
```

Finally, I've got this error : 
```
[Edge\QA\Task\ParallelExec]  '"/var/www/vendor/edgedesign/phpqa/../../../vendor/bin/psalm" --config=".ci/build/psalm-phpqa.xml" --show-info=true --use-ini-defaults --report=".ci/build/psalm.xml" --find-dead-code'
```

PHPQA generate this command line! The path to report is ok, but the path to the config file isn't the one I configured in my config file .phpqa.yml

**Comment by zdenekdrahos** [comment]
As you can see in [diff](https://www.diffchecker.com/QOF1Hkfw), phpqa adds `projectFiles` to XML. Your config isn't overwritten, but new file is created in `.ci/build/psalm-phpqa.xml`.

![Screenshot from 2019-04-08 19:33:18](https://user-images.githubusercontent.com/7994022/55744478-53f76700-5a35-11e9-9935-226d99a8045d.png)

If you don't like it, you can write custom Analyzer or don't use psalm in phpqa. See https://github.com/EdgedesignCZ/phpqa/pull/160#issuecomment-468759437

**Comment by webaaz** [comment]
It's really confusing

**Comment by zdenekdrahos** [comment]
phpqa's goal is [analyzing any directory](https://github.com/EdgedesignCZ/phpqa#why).

![Screenshot from 2019-04-09 16:15:06](https://user-images.githubusercontent.com/7994022/55807605-c6725080-5ae2-11e9-8f0d-ff2f81889aba.png)

You are talking about analyzing `src,tests`. Let's say, you want to analyze `src` directory, then `test` directory. psalm defines directories in `projectFiles`, so you can't use same XML file for each directory. That's why "dynamic XML file" is created.

It's not phpqa issue, that psalm defines directory configuration in XML file.
