### ISSUE TITLE
Override Generic.Files.LineLength in phpcs

### ISSUE THREAD

**Issue by marcteyssier** [EdgedesignCZ/phpqa#166]
Hi,

I want to override value Generic.Files.LineLength.limit to 150, but I don't found how can I do it.
In phpcs directly is really simple, I make a phpcs.xml with rule.
I cannot apply this in by phpqa.yml. I try to add a config file in php (with https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/.php_cs.dist) or the phpcs.xml but they are never read.

Can you help me ?
Regard

**Comment by zdenekdrahos** [comment]
Configure paths in [`.phpqa.yml`](https://github.com/EdgedesignCZ/phpqa/blob/master/.phpqa.yml):

* phpcs has `phpcs.standard` (https://github.com/EdgedesignCZ/phpqa/issues/25)
* php-cs-fixer has `php-cs-fixer.config` (https://github.com/EdgedesignCZ/phpqa/pull/160)

```yaml
phpcs:
    standard: phpcs.xml

php-cs-fixer:
    config: .php_cs.dist
```
