### ISSUE TITLE
Phpcpd names option?

### ISSUE THREAD

**Issue by aleixq** [EdgedesignCZ/phpqa#170]
Hello, 
I have a doubt. Does the phpcpd analyzer tool has any defined way to obey the extensions configuration option?
Is It not possible with the "--names" parameter in phpcpd command?
thank's for your time and your work

**Comment by zdenekdrahos** [comment]
`--names` isn't supported by current [phpcpd analyzer](https://github.com/EdgedesignCZ/phpqa/blob/v1.21.1/src/Tools/Analyzer/Phpcpd.php#L14). 

![Screenshot from 2019-06-09 09:31:08](https://user-images.githubusercontent.com/7994022/59156310-54de6080-8a99-11e9-9233-e39ee336c0dc.png)

It could be configured in [`.phpqa.yml`](https://github.com/EdgedesignCZ/phpqa/blob/v1.21.1/.phpqa.yml#L35) _(PR is welcomed)_ or [write custom analyzer](https://github.com/EdgedesignCZ/phpqa/pull/160#issuecomment-468759437).
