### ISSUE TITLE
phpstan fails for no reason

### ISSUE THREAD

**Issue by royalrex** [EdgedesignCZ/phpqa#171]
The phpstan and php-cs-fixer tool is failing for me when i run phpqa.

My system is: Windows 10, php 7.3
My project: I am analyzing the app (src) dir of a laravel (5.7) project.

I have installed phpqa globally, as well as all the different tools (with the exception of phpunit that I have not installed). commands: 
`composer global require edgedesign/phpqa --update-no-dev` 
and then 
`composer require jakub-onderka/php-parallel-lint jakub-onderka/php-console-highlighter phpstan/phpstan friendsofphp/php-cs-fixer:~2.2 vimeo/psalm sensiolabs/security-checker`

I also had issues with psalm, but upping memory helped on that issue.

End result of running `phpqa --analyzedDirs=app`
```
[phpqa]
+------------------+----------------+--------------+--------+------------------------------+
| Tool             | Allowed Errors | Errors count | Is OK? | HTML report                  |
+------------------+----------------+--------------+--------+------------------------------+
| phpmetrics       |                |              | ✓      | build//phpmetrics/index.html |
| phploc           |                |              | ✓      |                              |
| phpcs            |                | 450          | ✓      |                              |
| php-cs-fixer     |                | 0            | x      |                              |
| phpmd            |                | 156          | ✓      |                              |
| pdepend          |                |              | ✓      |                              |
| phpcpd           |                | 4            | ✓      |                              |
| phpstan          |                | 0            | x      |                              |
| psalm            |                | 293          | ✓      |                              |
| security-checker |                | 1            | ✓      |                              |
| parallel-lint    |                | 0            | ✓      |                              |
+------------------+----------------+--------------+--------+------------------------------+
| phpqa            |                | 904          | x      | build//phpqa.html            |
+------------------+----------------+--------------+--------+------------------------------+

[phpqa] Not installed tools: phpunit

[phpqa] Failed tools: php-cs-fixer, phpstan

```
Here is the output when I run the phpqa command with verbose option: 
`phpqa --analyzedDirs=app --verbose --tools=php-cs-fixer,phpstan` 
https://pastebin.com/B9EkdEA9

Thank you for your help and time.

**Comment by zdenekdrahos** [comment]
```
Errors count: 0
Is OK? x
```

It might be caused by `file_exists` in [RunningTool->analyzeResult](https://github.com/EdgedesignCZ/phpqa/blob/v1.21.1/src/RunningTool.php#L86). Can you experimentally modify the function? Is there a directory separator issue?

**Comment by zdenekdrahos** [comment]
@royalrex: What files are created in `dir C:\Projects\OnlineCity\message-service\build`? Is `php-cs-fixer.xml`  created?

![Screenshot from 2019-06-24 19:10:57](https://user-images.githubusercontent.com/7994022/60038196-ee218f80-96b3-11e9-9aa0-fb0c5cac3297.png)

_I ask, because I am no able to reproduce the error on [appveyor](https://ci.appveyor.com/project/zdenekdrahos/phpqa/builds/25503740)._
