### ISSUE TITLE
ERROR: The (unset) cast is deprecated

### ISSUE THREAD

**Issue by fosron** [EdgedesignCZ/phpqa#179]
Running Docker image with `phpqa tools` command outputs this and build fails.

```
ERROR: The (unset) cast is deprecated
in /phpqa/vendor/hoa/core/Core.php:146
```

**Comment by zdenekdrahos** [comment]
Same error happens on [travis](https://travis-ci.org/EdgedesignCZ/phpqa/jobs/558475094#L950) and build passed.
![Screenshot from 2019-07-26 15:17:09](https://user-images.githubusercontent.com/7994022/61954187-8fa04780-afb8-11e9-950b-d682bacd2de9.png)

And [build failed](https://travis-ci.org/EdgedesignCZ/phpqa/jobs/360633775) if there was phpunit error.
![Screenshot from 2019-07-26 15:20:43](https://user-images.githubusercontent.com/7994022/61954351-f7ef2900-afb8-11e9-8654-5cb349b925bd.png)

So I don't think that phpqa result is affected by `The (unset) cast is deprecated`.
If you don't like the message, then don't use or upgrade phpmetrics.
