### ISSUE TITLE
php-cs-fixer config path problem

### ISSUE THREAD

**Issue by almare** [EdgedesignCZ/phpqa#180]
For the most tools I use my own configuration files. All the files are located in the same folder as the phpqa.yml.

The strange thing is that  the config declaration for php-cs.dist has be set as an absolute path or relative to get it work. In any case it's not enough to set just the name of the config file like for the other tools. 

`php-cs-fixer:
    config: /app/custom/plugins/my-new-plugin/dev-ops/gitlab-ci/.php_cs.dist

phpmd:
    standard: phpmd.xml

phpunit:
    binary: null
    config: phpunit.xml
`
In my case the absolute paths of the above mentioned tools  are:
- /app/custom/plugins/my-new-plugin/dev-ops/gitlab-ci/.php_cs.dist
- /app/custom/plugins/my-new-plugin/dev-ops/gitlab-ci/phpmd.xml
- /app/custom/plugins/my-new-plugin/dev-ops/gitlab-ci/phpunit.xml

It look like the path to the .php_cs.dist file is not set correctly, because for phpmd and phpunit it works perfectly.

**Comment by zdenekdrahos** [comment]
You are right. php-cs-fixer's config isn't relative to `.phpqa.yml`. I'll fix it.

_Similar [phpunit issue](https://github.com/EdgedesignCZ/phpqa/commit/c7e9e1a) fixed in [v1.14](https://github.com/EdgedesignCZ/phpqa/blob/master/CHANGELOG.md#v1140)_

**Comment by almare** [comment]
Thank you
