### ISSUE TITLE
Phpstan fails because errorFormat / GetVersions returns not installed, although it is...

### ISSUE THREAD

**Issue by metalbote** [EdgedesignCZ/phpqa#182]
When trying to run a phpstan job, it quits with   
> The "--errorFormat" option does not exist. 

The error occured in Getversions()->analyseTool, which leads to "not installed" although it is. 
Digging further revealed, error is produced in findComposerPackages:
`$installedJson = COMPOSER_BINARY_DIR . '/../composer/installed.json';
 if (!is_file($installedJson)) {
  return [];
 }`

As normally composer/installed.json is placed at /vendor/composer/installed.json, i do not why here 
COMPOSER_BINARY_DIR is used.

After changing to 
`$installedJson = COMPOSER_VENDOR_DIR . '/composer/installed.json';`
it seems to work.

**Comment by metalbote** [comment]
FYI, i do not have custom bin dir, but custom vendor dir ;-)

**Comment by zdenekdrahos** [comment]
Ok. I reproduced the error with custom bin-dir. I didn't know about [vendor-dir](https://getcomposer.org/doc/06-config.md#vendor-dir). Let me know if you have any trouble.
