### ISSUE TITLE
phpqa report dashboard

### ISSUE THREAD

**Issue by li-adrienloiseau** [EdgedesignCZ/phpqa#186]
Hello,

On my "circleci" project, i'm launching all the tasks in parallel: 
<img width="726" alt="Capture d’écran 2019-09-30 à 17 02 12" src="https://user-images.githubusercontent.com/48802409/65890959-1223f980-e3a4-11e9-823f-004fa1a0e52f.png">
=> Directory reports: reports/phpcs/phpcs.xml -- reports/phpunit/phpunit.xml -- .....

Example cmd:
`qa/phpqa --report --buildDir reports/phpmetrics --analyzedDirs ./ --ignoredDirs features,data,scripts,public,vendor --tools=phpmetrics`

In the last job "reports" i want to create the dashboard reporting like this (**without re-running all tests**) based on the custom reports directories:
https://edgedesigncz.github.io/phpqa/report/phpqa.html

Any ideas ?

**Comment by zdenekdrahos** [comment]
You could merge [artifacts](https://github.com/EdgedesignCZ/phpqa/tree/gh-pages/report) from php jobs, then create custom homepage in [`reports` job](https://github.com/EdgedesignCZ/phpqa/blob/gh-pages/report/phpqa.html). It's definitely complicated and error-prone. One phpqa job or many reports _(without merging)_ might be simpler.

Anyway, this doesn't sound like use-case, that should be supported by phpqa. Please see https://github.com/EdgedesignCZ/phpqa/issues/151#issuecomment-428948890.

**Comment by li-adrienloiseau** [comment]
Ok for merging all jobs reports to the same directory in the reports job.
But how can i create custome homepage ?

**Comment by li-adrienloiseau** [comment]
> Ok for merging all jobs reports to the same directory in the reports job.
> But how can i create the custom homepage ?

@zdenekdrahos please ?

**Comment by zdenekdrahos** [comment]
1. I would take [current homepage](https://edgedesigncz.github.io/phpqa/report/phpqa.html#phpqa). 
1. Delete allowed and errors count _(it's basic homepage with links and without summary)_
1. Now it should work, if you copy artifacts from php jobs and this homepage into one directory

**Comment by li-adrienloiseau** [comment]
> 1. I would take [current homepage](https://edgedesigncz.github.io/phpqa/report/phpqa.html#phpqa).
==> Ok i'm getting this blank homepage 

> 2. Delete allowed and errors count _(it's basic homepage with links and without summary)_
==> How to delete allowed and errors count ? 

> 3. Now it should work, if you copy artifacts from php jobs and this homepage into one directory
==> It should work for the link page (ex: phpmectrics, phploc) but how to generate a new summary on the blank homepage ? 

I think it would be a good thing to be able to run the `phpqa --report` (with arg --no-tools) 
==> Task without launching tools! Based on the yml for the tools directories, ex: phpcs, phploc directories

This task would generate the homepage (+summary) by consuming previous reports based on the directory defined on yml ?

**Comment by zdenekdrahos** [comment]
Feel free to send a PR.

_As I said before (https://github.com/EdgedesignCZ/phpqa/issues/186#issuecomment-536649413), this is not phpqa priority. phpqa prefers running all tools with [parallel execution](https://github.com/EdgedesignCZ/phpqa#analyze), not proposed temporal coupling._

**Comment by almare** [comment]
It would be nice if we could add just for example a new menu entry point in the homepage. For example: I could merge my cypress results into my artefacts and just add the menu entries. Of course not all features are supported like cypress version, etc but i think this is really not necessary.
My use case would just be to get a fast and also nice report about my code and tests, which I also could deliver to my customer.
