### ISSUE TITLE
Error with PhpCpd progress helper

### ISSUE THREAD

**Issue by nbk195** [EdgedesignCZ/phpqa#19]
Hi Guys, 

first of all thanks for your tool, it's really great ! 
I encounter an issue with phpcpd running via phpqa. I've trying with parallel and non parallel execution, here the console output. 
````
Output for  /Users/Cyril/.composer/vendor/edgedesign/phpqa/../../bin/phpcpd --progress  --exclude=build --exclude=vendor --exclude=Tests --exclude=scripts --exclude=var --exclude=web "./src" --min-lines 5 --min-tokens 70 --log-pmd "./build/phpcpd.xml" 
phpcpd 2.0.4 by Sebastian Bergmann.



                                                                  
  [Symfony\Component\Console\Exception\InvalidArgumentException]  
  The helper "progress" is not defined.                           
                                                                  

phpcpd [--names NAMES] [--names-exclude NAMES-EXCLUDE] [--exclude EXCLUDE] [--log-pmd LOG-PMD] [--min-lines MIN-LINES] [--min-tokens MIN-TOKENS] [--fuzzy] [--progress] [--] [<values>]...



 [Edge\QA\Task\NonParallelExec]  Exit code 2  Time 68.85s

````

With phpcpd 2.0.1 with same arguments no problem.
Can you help me please ? 
Thanks
Cyril

**Comment by zdenekdrahos** [comment]
It looks like [bug in new version of phpcpd](https://github.com/sebastianbergmann/phpcpd/issues/132).

For now you can downgrade it, phpqa does not [restrict versions](https://github.com/EdgedesignCZ/phpqa/blob/master/composer.json#L30). 
phpcpd was upgraded in v1.5.0 ([v2.0.2 to v2.0.4](https://github.com/EdgedesignCZ/phpqa/commit/a4d09130ee86cb7618a7daee45de4d3c516a7210#diff-1da2c7edc898c70e5a79a9997c98ceccR1076)), so I guess that v2.0.2 should work:

```
composer global require sebastian/phpcpd:2.0.2
```

**Comment by nbk195** [comment]
Thanks a lot, 

after a small struggle with phpcpd dependencies everything is fine...

**Comment by zdenekdrahos** [comment]
I've just had the same problem. The bug occurs when `symfony/console` version 3.X is installed. So instead of downgrading phpcpd, you can downgrade `symfony/console` and have latest version of phpcpd.

```
{
    "require": {
        "symfony/console": "~2.8",
        "edgedesign/phpqa": ">=1.5",
    }
}
``` 

```
composer global update symfony/console sebastian/phpcpd
```

**Comment by eko3alpha** [comment]
Im using a docker image and ran into this same issue, I can confirm that part of @zdenekdrahos 's solution removes this issue.  I only changed the symfony/console version.

    composer global require 'edgedesign/phpqa' --update-no-dev "symfony/console:~2.8"

Here is a verbose output with only phpcpd

      [FileSystem\CleanDir] Cleaned build/
      [FileSystem\FilesystemStack] mkdir ["build\/"]
      0/1 [>---------------------------]   0% 0/1 [>---------------------------]   0% [ParallelExec] /composer/vendor/edgedesign/phpqa/../../bin/phpcpd --progress  --exclude=vendor "./" --min-lines 5 --min-tokens 70 --log-pmd "build//phpcpd.xml"

      [ParallelExec] Output for  /composer/vendor/edgedesign/phpqa/../../bin/phpcpd --progress  --exclude=vendor "./" --min-lines 5 --min-tokens 70 --log-pmd "build//phpcpd.xml" 

      1/1 [============================] 100%phpcpd 2.0.4 by Sebastian Bergmann.



                                                                  
     [Symfony\Component\Console\Exception\InvalidArgumentException]  
     The helper "progress" is not defined.                           
                                                                  

     phpcpd [--names NAMES] [--names-exclude NAMES-EXCLUDE] [--exclude EXCLUDE] [--log-pmd LOG-PMD] [--min-lines MIN-LINES] [--min-tokens MIN-TOKENS] [--fuzzy] [--progress] [--] [<values>]...



     [ParallelExec]  Exit code 1  Time 0.069s

     [phpqa] 
     +--------+----------------+--------------+--------+--------------------+
     | Tool   | Allowed Errors | Errors count | Is OK? | HTML report        |
     +--------+----------------+--------------+--------+--------------------+
     | phpcpd |                | 0            | x      | build//phpcpd.html |
     +--------+----------------+--------------+--------+--------------------+
     | phpqa  |                | 0            | x      | build//phpqa.html  |
     +--------+----------------+--------------+--------+--------------------+

     [phpqa] Failed tools: phpcpd

composer global require "symfony/console:~2.8" did the trick!

    +------------+----------------+--------------+--------+------------------------+
    | Tool       | Allowed Errors | Errors count | Is OK? | HTML report            |
    +------------+----------------+--------------+--------+------------------------+
    | phpcpd     |                | 0            | ✓      | build//phpcpd.html     |
    +------------+----------------+--------------+--------+------------------------+
    | phpqa      |                | 0            | ✓      | build//phpqa.html      |
    +------------+----------------+--------------+--------+------------------------+

**Comment by zdenekdrahos** [comment]
@eko3alpha: thanks for the docker image. 
I've copy-pasted your example to [readme](https://github.com/EdgedesignCZ/phpqa#docker). Feel free to send a PR with better tutorial :)

**Comment by eko3alpha** [comment]
Thanks! I certainly will.  I love how this project makes it so easy to use all the tools together.  I'm still wrapping my head around each individual tool and how to create custom rule sets.  Once I have everything together I'll certainly contribute!

Great work!

**Comment by zdenekdrahos** [comment]
> The bug occurs when symfony/console version 3.X is installed. So instead of downgrading phpcpd, you can downgrade symfony/console and have latest version of phpcpd.

[Install phpcpd dev-master](https://github.com/EdgedesignCZ/phpqa/pull/30/commits/51815b2) If you need `symfony/console 3.X`:

```
composer require sebastian/phpcpd:dev-master
```
