### ISSUE TITLE
Phpstan no longer depends on nette/neon

### ISSUE THREAD

**Issue by ndench** [EdgedesignCZ/phpqa#196]
Phpstan has moved it's development to phpstan/phpstan-src, and phpstan/phpstan is just a phar install. This means that it [no longer depends on nette/neon](https://github.com/phpstan/phpstan/commit/693f301d516da6c9bee4032bc12279a349430d82#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780).

The [Phpstan Analyser] uses nette/neon to process phpstan config, which now results in an error:

```
ERROR: Uncaught Error: Class 'Nette\Neon\Neon' not found in vendor/edgedesign/phpqa/src/Tools/Analyzer/Phpstan.php:32 
```

I think we have a few options to resolve this:
1. Require nette/neon in phpqa -> this means that users who don't want phpstan still must install it
2. Make users who want to use phpstan require nette/neon -> solves the problem, that's what I'm doing now but it is a bit annoying
3. Update the phpstan analyser to not create dynamic config -> other analysers are not creating dynamic config so I'm unsure as to why phpstan is

Personally I prefer option 3, but I'm open to the others as well. I'm happy to do the work for this if we can agree on the way forward.

**Comment by zdenekdrahos** [comment]
**ad 1)** phpqa won't preinstall [dependencies for suggested tools](https://github.com/EdgedesignCZ/phpqa#suggested-tools).

**ad 2)** It's already fixed (https://github.com/EdgedesignCZ/phpqa/pull/194), if you are using [`bin/suggested-tools.sh`](https://github.com/EdgedesignCZ/phpqa/blob/master/bin/suggested-tools.sh). 
You must install `neon`, even if you add notice to [composer.json](https://github.com/EdgedesignCZ/phpqa/blob/master/composer.json#L40), refine an error message etc. It's annonying, but it's the only way for suggested tool.

```
composer require phpstan/phpstan:~0.12.0 nette/neon
```

**ad 3)** Can you exclude files without config file? Or any other more [advanced config](https://github.com/EdgedesignCZ/phpqa/blob/master/src/Tools/Analyzer/Phpstan.php#L19)? I don't think so.

![](https://user-images.githubusercontent.com/7994022/71729187-5f01eb00-2e3f-11ea-89ef-a1d663de89ac.png)

**Comment by ndench** [comment]
That is for the speedy fox @zdenekdrahos, I think option 2 is the easiest and most effective one 👍.
