### ISSUE TITLE
How to use the docker image on a developer machine?

### ISSUE THREAD

**Issue by HenkPoley** [EdgedesignCZ/phpqa#199]
By default on Docker for Windows, any of the commands don't seem to mount the local source directory where you start the command.

Maybe add a few lines to say how to use the docker image to scan your local source files?

(Edit: I also notice that the included [psalm v1.1.9](https://packagist.org/packages/vimeo/psalm#1.1.9) is 1.5 years old)

**Comment by zdenekdrahos** [comment]
**1) Mount the local source directory**

You might need to use different environment variable. [`-v $PWD:/app`](https://github.com/EdgedesignCZ/phpqa#docker) probably does not work for Windows.

> -v $PWD : Passes docker the existing working directory for analyzing
> https://hub.docker.com/r/eko3alpha/docker-phpqa/

**2) Tools in docker image**

Please see https://github.com/EdgedesignCZ/phpqa/issues/159#issuecomment-452794397 and https://github.com/EdgedesignCZ/phpqa/issues/168#issuecomment-489180974

**Comment by HenkPoley** [comment]
Thanks for the reply. I'd still vote for including some of this in the readme 👍
