### ISSUE TITLE
Chaotic default output

### ISSUE THREAD

**Issue by VeN** [EdgedesignCZ/phpqa#2]
It would be nice to have better output by default.

- no cross output due to parallel excetution
- maybe not so verbose

![_2az5um5ug_d](https://cloud.githubusercontent.com/assets/260455/8125148/65f4daea-10e3-11e5-8dbd-82a2b67245d3.png)

**Comment by zdenekdrahos** [comment]
I don't think it's chaotic or cross outputted. It's default [Robo output in ParallelTask](https://github.com/Codegyre/Robo/blob/master/src/Task/Base/ParallelExec.php#L63). At first it prints list of used commands, then progress bar and result of each command.

Right now you can use `--quiet` option for no output at all. In next version 1.0.5 `--verbose` option will define if output from tools is printed.
