### ISSUE TITLE
Provide Phar in release

### ISSUE THREAD

**Issue by MacFJA** [EdgedesignCZ/phpqa#200]
Can you provide Phar of PHPQA in the release page ?

It could help to reduce the number of downloaded file and also remove any dependency lock (as the Phar itself contains its own dependency and therefor is self-contains)

And later on, it can be added to [Phive](https://phar.io/)
(already used by `infection`, `phpcpd`, `phploc`, `phpunit`, `squizlabs/php_codesniffer`, `phing`, `phpmd`, and lot more)

**Comment by zdenekdrahos** [comment]
Please see https://github.com/EdgedesignCZ/phpqa/issues/84#issuecomment-323078240
