### ISSUE TITLE
Psalm: check if directory exists before include them at <ignoreFiles>

### ISSUE THREAD

**Issue by elvishp2006** [EdgedesignCZ/phpqa#206]
When running the tool on CI, some `ignoredDirs` could not exists yet, and the psalm throw a error if a ignored directory not exists `Could not resolve config path to example/dist`. It's possible check if the directory exists before generate the `psalm-phpqa.xml`?

**Comment by almare** [comment]
Related problem [118](https://github.com/EdgedesignCZ/phpqa/issues/118) . Good catch @elvishp2006

**Comment by zdenekdrahos** [comment]
It seems to me as tool-specific settings. Phpqa should not care about too much internal details of every analyzer.

1. You define analyzed and ignored directories/files
2. phpqa transforms them to correct format
3. it's not phpqa responsibility, what happens, if directory does not exist, is not readable etc. 

I also think it could cause confusing behavior, if build configuration is magical and not explicit. Build could pass with skipped directories, but is that correct? If directory structure is changed and build config is not changed, then build should fail.
