### ISSUE TITLE
PhP 7.3 compatibility

### ISSUE THREAD

**Issue by pesek** [EdgedesignCZ/phpqa#210]
Hi,

recently our project switched to PhP7.3 and today we ran into some issues with our pipelines running phpqa. The problem is that the image uses PhP7.2 which does not support some syntax introduced in 7.3 (e.g. a trailing comma in a function call).

Because of this the parallel-lint task fails. Any suggestions for this problem? Is there a plan for upgrading to newer PhP version?

Thanks.

**Comment by zdenekdrahos** [comment]
Custom [docker](https://github.com/EdgedesignCZ/phpqa#docker) image is solution, please see links in https://github.com/EdgedesignCZ/phpqa/issues/199#issuecomment-590258608.
