### ISSUE TITLE
Support Symfony3 components

### ISSUE THREAD

**Issue by marcinlawnik** [EdgedesignCZ/phpqa#22]
As per title

**Comment by zdenekdrahos** [comment]
The upgrade would drop [support for php 5.4](https://github.com/EdgedesignCZ/phpqa/commit/86321eba9523686c587246ec935b1f14ebf7182a). I don't think that upgrading dependencies [this way](https://github.com/sebastianbergmann/phploc/commit/65c899fd5d61451b3f9237a7fc7f62ec20dd94fe) is  useful. Symfony components aren't core feature of phpqa. I guess that when robo releases [v1.0](https://github.com/consolidation-org/Robo/releases), then components will be updated. No need to hurry, isn't it?

**Comment by marcinlawnik** [comment]
Is there a reason you couldn't do "~2.8|~3.0"?
The reason I'm asking is that packages I have installed globally (like I also want phpqa) such as some laravel components require ~3.0 or ^3.0 (can't check, on mobile now) which makes me unable to install phpqa due to dependency conflicts.

**Comment by marcinlawnik** [comment]
Also, php 5.4 is unsupported now. The only supported release from the 5 line is 5.6. I see a value in keeping support for older versions, such as 5.5, but php 5.4 support ended 9 months ago ago (September 2015)
Source: http://php.net/eol.php

**Comment by marcinlawnik** [comment]
5.5 is also supported, but not for long

**Comment by zdenekdrahos** [comment]
> Is there a reason you couldn't do "~2.8|~3.0"

That's fine. I thought that 2.X version is dropped.
Can you create a PR?

**Comment by g4z** [comment]
This tools looks interesting, but it seems like a bit of a show-stopper that it's not possible to install it locally into a project using one of (or the) most popular PHP framework (Laravel) for months? 

I know i could install it globally (and i read your opinion about having a per-project composer.json style install), but we don't have the option to install it globally on the CI server. Our required "binaries" (phpunit, phpqa, etc...) must go in `.../vendors/bin/` in our project... so adding this tool to our project's composer.json is what we want to do.

I am referring to the fact that phpqa requires the old Symfony 2.8 components, but we cannot downgrade all our Symfony components just to install phpqa.

Is this going to be possible in the near future?

**Comment by zdenekdrahos** [comment]
@g4z: can you please confirm that https://github.com/EdgedesignCZ/phpqa/pull/30 solves the issue?

**Comment by g4z** [comment]
thanks for the speedy update! yes, it seems to have resolved the issue. i can install correctly now. 

but due to our minimum-stability policy, i had to test in a tmp branch and force dev-master versions for phpqa and henrikbjorn/lurker. this pulls in other newer versions of hoa/core, which seems to break half of our unit tests :( but that's another issue. 

thanks for the update! i hope to get this tool integrated into various projects soon.

**Comment by zdenekdrahos** [comment]
Version 1.7 is released, but you still need [dev-master dependencies](https://github.com/EdgedesignCZ/phpqa#symfony3-components)
