### ISSUE TITLE
Exit code is ignored from phpmd (parsing errors for new php syntax)

### ISSUE THREAD

**Issue by archfz** [EdgedesignCZ/phpqa#230]
Phpmd (v2.10.0) fails for a particular reason in this case (issue with trailing commas in function arguments): 
```
ERROR while parsing 
--------------------
Unexpected token: ), line: 56, col: 5, file
```
The exit code is printed correctly but phpqa considers this a success.

```
 73/73 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100% 
 [Edge\QA\Task\ParallelExec] Output for "/app/vendor/edgedesign/phpqa/../../../vendor/bin/phpmd" "src","tests" xml "/app/phpmd.xml"  --exclude /vendors/,/var/,/tests/_support/_generated/ --suffixes php --reportfile ".phpqa-report/phpmd.xml":


 [Edge\QA\Task\ParallelExec]  Exit code 3  Time 0.447s

[phpqa] 
+---------+----------------+--------------+--------+----------------------------+
| Tool    | Allowed Errors | Errors count | Is OK? | HTML report                |
+---------+----------------+--------------+--------+----------------------------+
| phpcs   | 0              | 0            | ✓      | .phpqa-report/phpcs.html   |
| phpmd   | 0              | 0            | ✓      | .phpqa-report/phpmd.html   |
| phpcpd  | 0              | 0            | ✓      | .phpqa-report/phpcpd.html  |
| phpstan | 0              | 0            | ✓      | .phpqa-report/phpstan.html |
+---------+----------------+--------------+--------+----------------------------+
| phpqa   |                | 0            | ✓      | .phpqa-report/phpqa.html   |
+---------+----------------+--------------+--------+----------------------------+

[phpqa] No failed tools
```

**Comment by zdenekdrahos** [comment]
I'm not sure if exit code strategy should be changed. phpqa counts phpmd [violations](https://github.com/EdgedesignCZ/phpqa#exit-code), not parsing errors. There was similar issue for some php7 syntax:

phpmd does not support new syntax. Different exit code is ignored, something is displayed in _"Parsing errors"_ tab in html report. Let's say phpqa respects phpmd's exit code. **You can't fix the build unless phpmd releases new version.** You could ignore the file, but it would be ignored for phpcs, phpstan etc.

I'm open to proposals. It could be overriden in config, but I don't think it should be default behavior. If you need it, you can use analysis without html report. CLI report analyzes only exit code:

```bash
 phpqa --tools phpmd:0 --output cli
```

**Comment by archfz** [comment]
Well it would be important to find a solution for this as in cases like this we literally tought everything was working fine, pipeline was passing, while in fact we were introducing lal kinds of violations.

I will think about it.

**Comment by zdenekdrahos** [comment]
Brainstorming notes...

---

**A) Similar solution like for [phpcs](https://github.com/EdgedesignCZ/phpqa/blob/master/src/Tools/Analyzer/Phpcs.php#L10)**

```php
        'errorsXPath' => [
            # ignoreWarnings => xpath
            false => '//checkstyle/file/error',
            true => '//checkstyle/file/error[@severity="error"]',
        ],
```

* `.phpqa.yml` contains `phpmd.countParsingErrors` (default: false)
* `countParsingErrors: false` -> count only `//pmd/file/violation`
* `countParsingErrors: true` -> count `//pmd/file/violation` and `//pmd/error`

Big disadvantage, that you can't fix the build unless phpmd releases new version.

---

**B) Display skipped errors somewhere**

Exit code strategy is not changed. Just display number of phpmd's parsing errors, phpcs's warnings somewhere in CLI output.

```bash
+---------+----------------+--------------+--------+----------------------------+
| Tool    | Allowed Errors | Errors count | Is OK? | HTML report                |
+---------+----------------+--------------+--------+----------------------------+
| phpcs   | 0              | 0 (10)       | ✓!     | .phpqa-report/phpcs.html   |
| phpmd   | 0              | 0 (2)        | ✓!     | .phpqa-report/phpmd.html   |
+---------+----------------+--------------+--------+----------------------------+
```

**Comment by zdenekdrahos** [comment]
Released in [v1.25](https://github.com/EdgedesignCZ/phpqa/releases/tag/v1.25.0) _([demo](https://edgedesigncz.github.io/phpqa/report/phpqa.html#phpmd))_

**Comment by archfz** [comment]
Well I also taught about this and you are right about this `You can't fix the build unless phpmd releases new version.`
I think for this reason the option B would be most valued. I have installed 1.25 but I cannot see option B, was that no implemented ?

**Comment by zdenekdrahos** [comment]
It's described in https://github.com/EdgedesignCZ/phpqa/pull/237:

* you can "hotfix" the build by editing `phpmd.countParsingErrors`
* warning is displayed in html report

![image](https://user-images.githubusercontent.com/7994022/121687361-8d6b0780-cac2-11eb-8e6c-62d7dde57c6a.png)
