### ISSUE TITLE
phpmextrics.xml output contains the data of PMD instead of phpmetrics analysis

### ISSUE THREAD

**Issue by akritiko** [EdgedesignCZ/phpqa#243]
I am running:
- the latest version of PHPQA --> v.1.25.0
- Ubuntu 21 OS
Thank you all in advance for any possible help!

**Comment by zdenekdrahos** [comment]
I don't think it can be fixed by phpqa. phpmetrics exports violations in this format:

```shell
--report-violations=<file>        File where XML violations report will be generated
```
