### ISSUE TITLE
HTML report failed to show

### ISSUE THREAD

**Issue by itsmoikala** [EdgedesignCZ/phpqa#244]
Hi, 

I running this command
> ./vendor/bin/phpqa --tools=phploc --report

The result
> DOMDocument::load(): I/O warning : failed to load external entity 

I need help with this.

**Comment by zdenekdrahos** [comment]
I don't think it can be fixed by phpqa. Probably no files to scan? I can reproduce it by using directory without php files

```
phpqa --tools phploc --report --analyzedDirs .github --verbose
```
