### ISSUE TITLE
checkstyle.xml without root element

### ISSUE THREAD

**Issue by hectorfarahani** [EdgedesignCZ/phpqa#250]
I set up phpqa, but the checkstyle.xml file is broken. It has no root element and no <?XML at the beginning. It starts and ends with <file and error reports.
Then in the CLI the output is:
```
 simplexml_load_file(): reports//checkstyle.xml:4: parser error : Extra content at the end of the document 
```

Could it be because of file permission or something preventing it from echoing the needed file start and endings?

**Comment by zdenekdrahos** [comment]
Use [verbose mode](https://github.com/EdgedesignCZ/phpqa#analyze), then you should see the cause of the empty xml.

```bash
phpqa --verbose --tools phpcs ...
```
