### ISSUE TITLE
ERROR: Use of "self" in callables is deprecated

### ISSUE THREAD

**Issue by davidmpaz** [EdgedesignCZ/phpqa#256]
Hi,

thanks for this project. Recently this is coming out in my pipeline. Any hints?

    ERROR: Use of "self" in callables is deprecated
    in /Users/davidmpaz/.composer/vendor/consolidation/robo/src/Task/Base/Exec.php:66

Thanks in advance,
David

**Comment by zdenekdrahos** [comment]
Upgrade robo. At the moment it is fixed in:

* `3.x` - https://github.com/consolidation/robo/pull/1136
* `4.x` - https://github.com/consolidation/robo/pull/1131

**Comment by davidmpaz** [comment]
Hi @zdenekdrahos, thanks for answering. I have latest version installed, from robo and as well phpqa, means this I need to chase which package of my QA tooling is using the wrong version?

Please keep in mind I am a user of this project, I use whatever version gets installed with it. I already did check and upgrade some packages to ensure proper version are in use.

This is my composer.json
```bash
❯ cat composer.json
{
    "require": {
        "edgedesign/phpqa": "^1.26",
        "php-parallel-lint/php-parallel-lint": "^1.3",
        "nette/neon": "^3.3",
        "phpunit/phpunit": "^9.5",
        "enlightn/security-checker": "^1.10",
        "qossmic/deptrac-shim": "^1.0.0",
        "friendsofphp/php-cs-fixer": "^3.0.0",
        "symfony/thanks": "^1.2",
        "phpstan/phpstan-symfony": "^1.2",
        "phpstan/phpstan": "^1.8"
    },
    "config": {
        "allow-plugins": {
            "phpstan/extension-installer": true,
            "symfony/thanks": false
        }
    }
}
```

thanks advance,
David

**Comment by zdenekdrahos** [comment]
phpqa does not specify the robo version, so you can install whatever version you need. One of these should work:

```shell
composer require consolidation/robo:3.x-dev
composer require consolidation/robo:4.x-dev
```
