### ISSUE TITLE
Summary XSL to highlight classes/method with complexity

### ISSUE THREAD

**Issue by garex** [EdgedesignCZ/phpqa#31]
Gist: https://gist.github.com/garex/5cd9b97c40f3369cb8cf60f253868df9

Example output on symfony/console.

![image](https://cloud.githubusercontent.com/assets/77981/19301081/e042565e-9087-11e6-92f9-f0b1eb7a4744.png)

**Comment by garex** [comment]
Nice ))

**Comment by zdenekdrahos** [comment]
@garex: thanks for the XSL template. 

Check [PDepend report](https://edgedesigncz.github.io/phpqa/report/phpqa.html) in version [v1.7.1](https://github.com/EdgedesignCZ/phpqa/releases/tag/v1.7.1) . Feel free to send a PR with even better report.

**Comment by garex** [comment]
Already checked. Now I can use `phpqa` out-of-the-box in nice style.

**Comment by zdenekdrahos** [comment]
[v1.7.2](https://edgedesigncz.github.io/phpqa/report/phpqa.html) has even better style. At least I hope so...
