### ISSUE TITLE
phpcpd needs dev-master for --progress

### ISSUE THREAD

**Issue by mario-naether** [EdgedesignCZ/phpqa#36]
Hallo,

the last tagged version of sebastian/phpcpd:2.0.4 has a bug with the progressBar.
https://github.com/sebastianbergmann/phpcpd/issues/132

The temporary solution is to update the phpcpd package to dev-master or remove --progress option in your CodeAnalyseTask.php.

**Comment by zdenekdrahos** [comment]
It happens in symfony3/console (https://github.com/EdgedesignCZ/phpqa/issues/19). 
It's already documented in [readme](https://github.com/EdgedesignCZ/phpqa#symfony3-components).

Thanks anyway.
