### ISSUE TITLE
Set multiple analyzedDirs

### ISSUE THREAD

**Issue by mario-naether** [EdgedesignCZ/phpqa#38]
Hi, wounld to analys multiple folders in one command. Like this 
`vendor/bin/phpqa --verbose --analyzedDir ./src1 ./src2 --report`

The following error occurred on starting this command.
" Too many arguments, expected arguments "command"."

To you have any idea how this works?

**Comment by zdenekdrahos** [comment]
Right now only one directory is supported. 
You have to [analyze root directory and ignore](https://github.com/EdgedesignCZ/phpqa#project-with-multiple-directories-src-tests-) remaining directories.

```
vendor/bin/phpqa --analyzedDir ./ --ignoredDirs=vendor,other-non-src-directory
```

But I'll look into supporting multiple directories. It looks like that only phpmetrics doesn't support multiple directories.

**Comment by zdenekdrahos** [comment]
phpqa [v1.8](https://github.com/EdgedesignCZ/phpqa/releases/tag/v1.8.0) supports analyzing multiple directories:

```
vendor/bin/phpqa --verbose --analyzedDirs ./src1,./src2 --report
```
