### ISSUE TITLE
Changing composer bin-dir breaks tools path

### ISSUE THREAD

**Issue by sojki** [EdgedesignCZ/phpqa#46]
When you use phpqa in project locally and you change composer bin-dir, than phpqa cannot find binaries for tools (phpcpd, phpmd, ...).

PHPQA only checks location of autoload.php, but then expects bin folder in same path. Maybe the bin folder should be checked too. 

Path of bin folder can be (according to composer docs) changed in two ways
- Setting the bin-dir configuration setting in composer.json
- Setting the environment variable COMPOSER_BIN_DIR

Or [*the simple solution*] PHPQA can only trigger exception if the tool in expected path is not found (Yes, you can see it in exit code 127, but this is easy to overlook).

**Comment by zdenekdrahos** [comment]
Fixed in [v1.9](https://github.com/EdgedesignCZ/phpqa/releases/tag/v1.9.0)
