### ISSUE TITLE
Twig_loader_filesystem not found with new phpmetrics

### ISSUE THREAD

**Issue by mario-naether** [EdgedesignCZ/phpqa#49]
Hi, i updated the phpmetrics Package to 2.*
The twig integration has been removed in this new version and do you need twig in your report file generation. 
So you should add the Twig ~1 to your dependencies. 
Mfg Mario

**Comment by zdenekdrahos** [comment]
Thanks for letting me know. I didn't know that phpmetrics has released new version.

Excluding the twig issue, is everything ok with phpqa + phpmetrics v2?

**Comment by mario-naether** [comment]
Hallo,
unfortunately not.
I starting the PHP QA 
`vendor/bin/phpqa --analyzedDirs ./examples/src/ --buildDir ./build/logs --report -v`

That starting this command with error output of phpmetrics.
` Output for  \vendor\edgedesign\phpqa/../../../vendor/bin/phpmetrics "./examples/src/" --extensions php  --excluded-dirs="vendor" --offline --report-html "./build/logs/phpmetrics.html" --report-xml "./build/logs/phpmetrics.xml"

Directory ./build/logs/phpmetrics.xml does not exist

Usage:

    phpmetrics [...options...] <directories>

Required:

    <directories>                       List of directories to parse, separated by a comma (,)

Optional:

    --exclude=<directory>               List of directories to exclude, separated by a comma (,)
    --extensions=<php,inc>              List of extensions to parse, separated by a comma (,)
    --report-html=<directory>           Folder where report HTML will be generated
    --report-violations=<file>          File where XML violations report will be generated
    --git[=</path/to/git_binary>]       Perform analyses based on Git History (default binary path: "git")
    --junit[=</path/to/junit.xml>]      Evaluates metrics according to JUnit logs
    --quiet                             Quiet mode
    --version                           Display current version

Examples:

    phpmetrics --report-html="./report" ./src

        Analyze the "./src" directory and generate a HTML report on the "./report" folder


    phpmetrics --report-violations="./build/violations.xml" ./src,./lib

        Analyze the "./src" and "./lib" directories, and generate the "./build/violations.xml" file. This file could
        be read by any Continuous Integration Platform, and follows the "PMD Violation" standards.
`

A working command can be:
` vendor/bin/phpmetrics "./examples/src/"  --excluded-dirs="vendor" --offline --report-html="./build/logs/phpmetrics.html" --report-violations="./build/logs/phpmetrics.xml" 
`
