### ISSUE TITLE
phpcs warnings should not be reported as errors

### ISSUE THREAD

**Issue by bblasius** [EdgedesignCZ/phpqa#53]
phpcs warnings count as errors, exit with code 1 and break ci builds.

this could be avoided by changing the errorsXPath setting of phpcs.
change phpqa/src/CodeAnalysisTasks.php : 26 from "'errorsXPath' => '//checkstyle/file/error'" to "'errorsXPath' => '//checkstyle/file/error[@severity="error"]'".

**Comment by zdenekdrahos** [comment]
You are right, phpqa does not distinguish between errors and warnings. 
I think that Jenkins does it too so I have never thought about it.

Would it be okay for you to set _"ignore warnings"_ in [.phpqa.yml](https://github.com/EdgedesignCZ/phpqa/blob/master/.phpqa.yml#L1)?

**Comment by bblasius** [comment]
an "ignore warnings" setting in .phpqa.yml would be absolutely fine for me
