### ISSUE TITLE
Support PHP CS Fixer 

### ISSUE THREAD

**Issue by keradus** [EdgedesignCZ/phpqa#60]
Hi.
Are there any chances that you would add `PHP CS Fixer ` to collection of supported tools ?

**Comment by zdenekdrahos** [comment]
How would you like to use `php-cs-fixer` in phpqa?

It can be added to [suggested tools](https://github.com/EdgedesignCZ/phpqa#suggested-tools). But I have a doubt about usefulness. phpqa analyzes code. If you run analysis twice, you'll get the same result. `php-cs-fixer` isn't like that. It can fix code in CI build, but changes aren't committed. Wouldn't be better to install phpqa and php-cs-fixer separately?

**Comment by keradus** [comment]
in same way that `phpcpd` or `phpmd` or anything that is currently supported.
`PHP CS Fixer` could fix indeed, but it could also generate violations report.

**Comment by mastercoding** [comment]
@zdenekdrahos You are right that changing code style errors in the ci build does not make any sense. However, if php-cs-fixer is run with junit as output (optionally in "dry-run" mode, to not change anything and produce the same results every time), it is a static analyser just like phpcs.

**Comment by zdenekdrahos** [comment]
Ok. `php-cs-fixer` gonna be in the next release.
I'll ask you for your review in a PR.
