### ISSUE TITLE
new release of PHPCS 3.0 dosn't work

### ISSUE THREAD

**Issue by mario-naether** [EdgedesignCZ/phpqa#64]
Hi,

the project "squizlabs/php_codesniffer" has released the version 3.0 with a completely refactoring of code.
So the `PHP_CodeSniffer` class dosn't exists and the PHPQA Tool crashes .

```
 [FileSystem\FilesystemStack] mkdir [".\/build\/logs"]

PHP Fatal error:  Class 'PHP_CodeSniffer' not found in ***/vendor/edgedesign/phpqa/src/CodeAnalysisTasks.php on line 215

PHP Stack trace:
```

https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/3.0.0

**Comment by zdenekdrahos** [comment]
@mario-naether: phpcs [v3](https://github.com/EdgedesignCZ/phpqa/issues/65) and robo  [v1](https://github.com/EdgedesignCZ/phpqa/pull/61) is supported in [master](https://travis-ci.org/EdgedesignCZ/phpqa/jobs/229618044#L393).  Could you try it? Thanks

```
composer update edgedesign/phpqa:dev-master
```

**Comment by mario-naether** [comment]
@zdenekdrahos 
the dev-master works for me with CodeSniffer 3.0
