### ISSUE TITLE
Latest version of phploc removed progress option

### ISSUE THREAD

**Issue by auroraeosrose** [EdgedesignCZ/phpqa#72]
Could do a PR to just remove the progress being passed, but it might be better to make it an argument option to phploc

**Comment by zdenekdrahos** [comment]
Removed in [v4.0](https://github.com/sebastianbergmann/phploc/blob/master/ChangeLog.md#400---2017-06-06)

For now use `v3`. Based on changelog latest version only removed some functionality. 
Or is there some undocumented reason why `v4` is preferred?

**Comment by auroraeosrose** [comment]
I'm using PHP 7.1 which plays a lot better with version 4.0
