### ISSUE TITLE
phpunit & code coverage support

### ISSUE THREAD

**Issue by cbastienbaron** [EdgedesignCZ/phpqa#80]
Hi,
TY for this pratical tool ;) one line command save my time ! ;)
It's possible to integrate phpunit and particulary code coverage integrate in the UI ? 

Thanks in advance for you're response 
seb

**Comment by zdenekdrahos** [comment]
Phpunit (or codeception, phpspec, ...) won't be a part of phpqa.
phpqa is collection of analyzers, phpunit is different:

> We deal with 2 kinds of require-dev dependencie. The ones that work "on-top" of your code or don't touch your code at all, tools like Phing, phpDocumentor or Codesniffer. On the other hand, we have to deal with tools that closely "interact" with your code, tools like PHPUnit. The tools that work "on-top" of your code can easily be replaced by their .phar versions and you will not notice any difference. The "problem" are tools like PHPUnit which interact closely which your code
> https://blog.bitexpert.de/blog/solving-the-require-dev-problem/

**Comment by cbastienbaron** [comment]
it's a part of assurance quality of code... and the main goal of phpqa (IMHO), it's a facade / proxy / facilitator to others tools to analyse / get metrics of applicative in one cmd, and not care of "dev/deps" of project (less download during ci-cycles), and one more thing, phpqa.html let us to group all analyses in a cool way (for visual interact ex: qa.my.-project.staging.toto.com) and the code coverage can be a great place here. u get my point of view , or there is no way ? :)

**Comment by zdenekdrahos** [comment]
No way to run phpunit via `phpqa`. 

It could be possible to add "other files" or links to phpqa report. 
[.phpqa.yml](https://github.com/EdgedesignCZ/phpqa/blob/master/.phpqa.yml#L37) would contain something like

```
report:
    external:
       PHPUnit: var/phpunit/coverage/
       testdox: var/phpunit/testdox.html
```

But that's a tricky and I don't want to do that right now. 
For now I recommend to [separate phpunit and phpqa](https://github.com/EdgedesignCZ/phpqa/blob/master/.travis.yml#L23).

**Comment by cbastienbaron** [comment]
there is 2 schools here ( like often times ), this workaround (external) for code coverage is indeed what i need. 
thinking flexibility is a must have ... (specially for render results)

**Comment by zdenekdrahos** [comment]
Phpunit reports in phpqa are nice, but running phpunit from phpqa is tricky...
Experimental support in https://github.com/EdgedesignCZ/phpqa/pull/82. Could you check it out and try it?
```
composer update edgedesign/phpqa:dev-windows-compatibility
```

**Comment by cbastienbaron** [comment]
works like a charms ! perfect :+1:
