### ISSUE TITLE
vimeo/psalm support

### ISSUE THREAD

**Issue by MacFJA** [EdgedesignCZ/phpqa#85]
The project https://github.com/vimeo/psalm give good insight about code quality and possible misconception.

It would be great if **phpqa** have it in its available tools

**Comment by MacFJA** [comment]
I started to write the code for this feature.

Right now I have some trouble to get the number of errors (I open a PR on vimeo/psalm#206 to solve this)

**Comment by zdenekdrahos** [comment]
Good job, @MacFJA. 

How do you plan to use `--analyzedDirs`/`--ignoredDirs/--ignoredFiles` in `projectFiles`?
I would prefer similar process like in [phpstan](https://github.com/EdgedesignCZ/phpqa/blob/master/src/CodeAnalysisTasks.php#L372):

1. load xml config file from `.phpqa.yml`
2. update `projectFiles` save a new xml file in `--buildDir/psalm-phpqa.xml`

_BTW you can develop the psalm support even without XML and number of errors. If you use [` OutputMode::RAW_CONSOLE_OUTPUT`](https://github.com/EdgedesignCZ/phpqa/blob/master/src/CodeAnalysisTasks.php#L85) then [CLI output](https://edgedesigncz.github.io/phpqa/report/phpunit.html) is used in report._

**Comment by MacFJA** [comment]
I exactly use what is done on phpstan: If no config is provided in the `.phpqa.yml`, I generate a config file base on `--analyseDirs`, `--ignoredDirs` and `--ignoredFiles`.

My code is ready, just waiting my PR to be validated ( Here some screenshot of the rendering [Report HTML - 1](https://screenshot.net/d2npjc8), [Report HTML - 2](https://screenshot.net/p4yr3s6))

**Comment by zdenekdrahos** [comment]
@MacFJA: the code has been released in [version 0.3.55](https://github.com/vimeo/psalm/commits/0.3.55).
I'm already looking forward to a phpqa PR. Screenshots look great!
